### ISSUE TITLE
Look at related work using social media APIs

### ISSUE THREAD

**Issue by emily-tew** [office-for-statistics-regulation/Automation_dashboard#15]

**Comment by emily-tew** [comment]
This is a good example of using Tweepy (Twitter's API for Python): https://www.dataquest.io/blog/streaming-data-python/ .

They even have open source code on GitHub which we can take and modify to meet our needs: https://github.com/dataquestio/twitter-scrape

**Comment by emily-tew** [comment]
rtweet looks to be a very good R alternative: https://rtweet.info/

**Comment by LewisJack87** [comment]
quicknews allows you to scrape Googles rss  feed for news going back two weeks. It should be possible to gather and store the news so you can get a time series.

https://github.com/jaytimm/quicknews

**Comment by LewisJack87** [comment]
This is an example of doing something similar to quicknews on Python.

https://medium.com/@ezzatdemnati/web-scraping-news-data-rss-feeds-python-and-google-cloud-platform-7a0df2bafe44
