### ISSUE TITLE
Differences in language (R or Python)

### ISSUE THREAD

**Issue by emily-tew** [office-for-statistics-regulation/Automation_dashboard#21]
- Web Scraping
- Social Media (Twitter, LinkedIn?)
- Storage solutions 
- Visualisation (dashboard apps, plots)
- Compatibility with other languages

**Comment by LewisJack87** [comment]
Visualisation - R has a larger data analysis function than Python. Yo have the ability to create widgets and interactive charts with R using leaflet and ggplot2. Though looking at the Python dash library they seem to be catching R in this area. RShiny allows people without much programming experience to create dashboards quite easily, Pythons Dash is similar but as mature as Shiny and doesn't have as many add on's.

Web Scraping - It is easy to download a web page in the both languages. When scraping a web page for specific data the Python code is shorter and less complex than R. It also easier to data in formats like JSON in Python, with R the code for this longer and more complicated.

Compatibility - Python is a general programming language, so it is easier to deploy apps and models into other software. You can run Python in R using reticulate and you can run R in Python using rpy2.

Storage solutions - Both languages are able to run in cloud; Google Drive, Amazon, IBM Data Joy etc.. There doesn't seem to be any difference. All have free options though we may need to pay depending on how much data we use.
